---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gitopssecret-snappcloud-io-v1alpha1-agekey
  failurePolicy: Fail
  name: magekey.kb.io
  rules:
  - apiGroups:
    - gitopssecret.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agekeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gitopssecret-snappcloud-io-v1alpha1-agesecret
  failurePolicy: Fail
  name: magesecret.kb.io
  rules:
  - apiGroups:
    - gitopssecret.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agesecrets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gitopssecret-snappcloud-io-v1alpha1-agekey
  failurePolicy: Fail
  name: vagekey.kb.io
  rules:
  - apiGroups:
    - gitopssecret.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agekeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gitopssecret-snappcloud-io-v1alpha1-agesecret
  failurePolicy: Fail
  name: vagesecret.kb.io
  rules:
  - apiGroups:
    - gitopssecret.snappcloud.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agesecrets
  sideEffects: None
